import java.io.File

class ManifoldMC {
    companion object {
        public fun setupPreprocessor(
            compilerArgs: MutableList<String>?,
            loader: String,
            parent: File,
            mcString: String,
            isActive: Boolean,
            clearMainProject: Boolean
        ) {
            val mcVers = listOf("1.18.2", "1.19.2", "1.20.1", "1.21.1", "26.1.2")
            val mcIndex = mcVers.indexOf(mcString)
            val argList = ArrayList<String>()

            // Until 1.21.x the project used values such as 201 and 211. The
            // new year-based Minecraft versions have no leading "1." to trim.
            val numericalMC = if (mcString.startsWith("1.")) {
                mcString.substring(2).replace(".", "")
            } else {
                mcString.replace(".", "")
            }
            argList.add("MC=$numericalMC")
            argList.add("mc=$numericalMC")

            for (i in mcVers.indices) {
                val normalizedVersion = mcVers[i].replace(".", "_")
                val mcStr = if (normalizedVersion.startsWith("1_")) normalizedVersion.substring(2) else normalizedVersion
                if (mcIndex < i) {
                    argList.add("BEFORE_$mcStr")
                    argList.add("before_$mcStr")
                }
                if (mcIndex <= i) {
                    argList.add("UPTO_$mcStr")
                    argList.add("upto_$mcStr")
                }
                if (mcIndex == i) {
                    argList.add("CURRENT_$mcStr")
                    argList.add("current_$mcStr")
                }
                if (mcIndex > i) {
                    argList.add("NEWER_THAN_$mcStr")
                    argList.add("newerthan_$mcStr")
                }
                if (mcIndex >= i) {
                    argList.add("AFTER_$mcStr")
                    argList.add("after_$mcStr")
                }
            }

            when (loader) {
                "fabric" -> {
                    argList.add("FABRIC")
                    argList.add("fabric")
                }
                "forge" -> {
                    argList.add("FORGE")
                    argList.add("FORGELIKE")
                    argList.add("forge")
                    argList.add("forgelike")
                }

                "neoforge" -> {
                    argList.add("NEO")
                    argList.add("FORGELIKE")
                    argList.add("neo")
                    argList.add("forgelike")
                }
            }

            val sb = StringBuilder().append("# DO NOT EDIT - GENERATED BY THE BUILD SCRIPT\n")
            for (arg in argList) {
                compilerArgs?.add("-A$arg")
                sb.append(arg)
                if (!arg.contains("="))
                    sb.append("=")

                sb.append("\n")
            }

            File(parent, "build.properties").writeText(sb.toString())

            if (isActive)
                File(parent, "../../src/main/build.properties").writeText(sb.toString())

            if (clearMainProject)
                File(parent, "../../src/main/build.properties").delete()
        }
    }
}
